# @package models
# Model Configuration with Enhanced Parameter Coverage

# Global model settings
confidence_threshold: 0.5  # Global default, can be overridden per model

# Device settings (can be overridden globally or per model)
device: "cuda"  # Options: "cuda", "cpu"

keypoints:
  prune_patterns: ["foot"]

# YOLO Configuration
yolo:
  # Model paths
  pose_model_path: "weights/yolo11x-pose.pt"
  detection_model_path: "weights/yolo11x.pt"
  
  # Inference settings
  confidence_threshold: 0.25  # Override global for YOLO

# ViTPose Configuration  
vit:
  # Model settings
  model_name: "usyd-community/vitpose-plus-huge"  
  # Detection settings (uses YOLO for person detection)
  confidence_threshold: 0.5


triangulation:
  use_bundle_adjustment: True