# @package models
# Model Configuration with Enhanced Parameter Coverage

# Global model settings
confidence_threshold: 0.5  # Global default, can be overridden per model

# Device settings (can be overridden globally or per model)
device: "cpu"  # Options: "cuda", "cpu"

keypoints:
  prune_patterns: ["foot"]

# YOLO Configuration
yolo:
  # Model paths
  pose_model_path: "weights/yolo11l-pose.pt"
  detection_model_path: "weights/yolo11l.pt"

# ViTPose Configuration  
vit:
  # Model settings
  model_name: "usyd-community/vitpose-plus-large"  


triangulation:
  use_bundle_adjustment: True