# @package models
# Model Configuration with Enhanced Parameter Coverage

# Global model settings


# Device settings (can be overridden globally or per model)
device: "cpu"  # Options: "cuda", "cpu"

keypoints:
  prune_patterns: ["foot"]

# YOLO Configuration
yolo:
  # Model paths
  pose_model_path: "weights/yolo11x-pose.pt"
  confidence_threshold: 0.7

# ViTPose Configuration  
vit:
  # Model settings
  model_name: "usyd-community/vitpose-plus-huge"  
  detection_model_path: "weights/yolov8x-worldv2.pt"
  confidence_threshold: 0.6

triangulation:
  use_bundle_adjustment: False