# @package _global_
defaults:
  - logging: default
  - models: default
  - paths: dataset  # Default paths, will be overridden per job
  - pipeline: dataset  # Default pipeline, will be overridden per job
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override /hydra/launcher: basic

# Default mode (will be overridden by multirun sweep)
mode: "dataset"

project:
  name: "pose_estimation_pipeline"

hydra:
  mode: MULTIRUN
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: output
    subdir: ${mode}
  sweeper:
    params:
      mode: dataset,video
      paths: dataset,video  # This will switch paths configs
      pipeline: dataset,video  # This will switch pipeline configs