# Video Processing Configuration
defaults:
  - logging: default
  - models: default
  - paths: dataset
  - pipeline: dataset
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Override mode for dataset processing
mode: "dataset"

project:
  name: "pose_estimation_pipeline"

hydra:
  output_subdir: null
  run:
    dir: .
