# Video Processing Configuration
defaults:
  - logging: default
  - models: default
  - paths: video
  - pipeline: video
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Override mode for video processing
mode: "video"

project:
  name: "pose_estimation_pipeline"

hydra:
  output_subdir: null
  run:
    dir: .
